/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */



// Create all the GUI controls. 
// autogenerated do not edit

import java.awt.Font;
import java.awt.*;

final String font = "Open Sans";

public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.GOLD_SCHEME);
  G4P.setMouseOverEnabled(false);
  if(frame != null){
    frame.setTitle("Sketch Window");
  }
  TTL = new GLabel(this, 310, 200, 170, 110);
  TTL.setFont(new Font(font ,Font.PLAIN, 85));
  TTL.setText("3");
  TTL.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  TTL.setOpaque(false);
}

public void createGUI2(){
  ansA = new GLabel(this, 100, 388, 250, 40);
  ansA.setText("My label");
  ansA.setTextBold();
  ansA.setOpaque(false);
  ansA.setFont(new Font(font, Font.PLAIN, 20));
  ansA.setTextAlign(GAlign.LEFT, GAlign.LEFT);
  
  ansC = new GLabel(this, 100, 429, 250, 40);
  ansC.setText("My label");
  ansC.setTextBold();
  ansC.setOpaque(false);
  ansC.setFont(new Font(font, Font.PLAIN, 20));
  ansC.setTextAlign(GAlign.LEFT, GAlign.LEFT);
  
  ansB = new GLabel(this, 450, 388, 250, 40);
  ansB.setText("My label");
  ansB.setTextBold();
  ansB.setOpaque(false);
  ansB.setFont(new Font(font, Font.PLAIN, 20));
  ansB.setTextAlign(GAlign.LEFT, GAlign.LEFT);
  
  ansD = new GLabel(this, 450, 428, 250, 40);
  ansD.setText("My label");
  ansD.setTextBold();
  ansD.setOpaque(false);
  ansD.setFont(new Font(font, Font.PLAIN, 20));
  ansD.setTextAlign(GAlign.LEFT, GAlign.LEFT);
  
  pointsField = new GLabel(this, 15, 5, 200, 40);
  pointsField.setText("0");
  pointsField.setTextBold();
  pointsField.setLocalColorScheme(GCScheme.RED_SCHEME);
  pointsField.setOpaque(false);
  pointsField.setFont(new Font(font, Font.PLAIN, 24));
  pointsField.setTextAlign(GAlign.LEFT, GAlign.LEFT);
  
  prompt= new GLabel(this,50,328,700,56);
  prompt.setText("MyLabel");
  prompt.setTextBold();
  prompt.setOpaque(false);
  prompt.setFont(new Font(font, Font.PLAIN, 24));
  
  time_left= new GLabel(this,550,5,250,40);
  time_left.setText("Infinity");
  time_left.setTextBold();
  time_left.setOpaque(false);
  time_left.setFont(new Font(font, Font.PLAIN, 24));
  time_left.setLocalColorScheme(GCScheme.RED_SCHEME);
  time_left.setTextAlign(GAlign.LEFT, GAlign.LEFT);
  
  image = new GImageButton(this, 0, 50, 800, 275, new String[] { "geo1.png"});
  image.setEnabled(false);
}

public void reset_fields(){
 TTL.setText("");
 ansA.setText("");
 ansB.setText("");
 ansC.setText("");
 ansD.setText("");
 pointsField.setText("");
 prompt.setText("");
 time_left.setText("");
 image = null;
 setImage("transparent.png");
}

public void setImage(String img){
   image = new GImageButton(this, 0, 50, 800, 275, new String[] {img});
}
// Variable declarations 
// autogenerated do not edit
GLabel TTL; 
GLabel ansA,ansB,ansC,ansD,pointsField,prompt,time_left;
GImageButton image; 
